

DROP TABLE IF EXISTS foodpanda
CREATE TABLE foodpanda(
customer_id	VARCHAR(15),
gender	VARCHAR(15),
age	VARCHAR(25),
city	VARCHAR(25),
signup_date	DATE,
order_id	VARCHAR(25),
order_date	DATE,
restaurant_name	VARCHAR(25),
dish_name	VARCHAR(25),
category	VARCHAR(25),
quantity	INT,
price	FLOAT,
payment_method	VARCHAR(25),	
order_frequency	INT,
last_order_date	DATE,
loyalty_points	INT,
churned	VARCHAR(25),
rating	INT,
rating_date	DATE,
delivery_status	VARCHAR(25),
age_int INT
)

SELECT *
FROM foodpanda

--	1  What is the total number of unique orders in the dataset?

SELECT
	COUNT(DISTINCT(order_date)) AS nr_of_unique_orders
FROM foodpanda

-- 2  How many unique customers are currently in our database?

SELECT
	COUNT(DISTINCT(customer_id)) AS nr_of_unique_customers
FROM foodpanda

-- 3  What is the average price of a dish across all restaurants?

SELECT
	ROUND(AVG(price)::numeric,2) AS avg_price
FROM foodpanda

-- 4  Which city has the highest volume of orders?
WITH table1
AS
(
SELECT
	city,
	COUNT(order_id) as nr_of_orders
FROM foodpanda
GROUP BY 1
)

SELECT
	city,
	RANK() OVER(ORDER BY nr_of_orders DESC)
FROM table1

-- 5  What is the most preferred payment method used by customers?

SELECT
	payment_method,
	COUNT(payment_method)
FROM foodpanda
GROUP BY 1
ORDER BY 2 DESC

-- 6  How many distinct restaurants are active on the platform?

SELECT
	COUNT(DISTINCT(restaurant_name))
FROM foodpanda

-- 7  What is the average loyalty points balance per customer?

WITH table1
AS
(
SELECT
	DISTINCT customer_id AS customer,
	loyalty_points
FROM foodpanda
)
SELECT
	customer,
	ROUND(AVG(loyalty_points)::numeric,2)
FROM table1
GROUP BY 1

-- 8  How many orders have a delivery_status of "Cancelled" or "Failed"?

SELECT
	COUNT(*)
FROM foodpanda
WHERE delivery_status = 'Cancelled' OR
delivery_status = 'Failed'

-- 9  What is the gender distribution of our customer base?

SELECT
	gender,
	COUNT(gender)
FROM foodpanda
GROUP BY 1

-- 10  What is the earliest and latest order_date in this dataset?

SELECT
	MIN(order_date) AS first_order,
	MAX(order_date) AS last_order
FROM foodpanda

-- 11  What is the total revenue generated by each restaurant?

SELECT
	restaurant_name,
	ROUND(SUM(price)::numeric,2)
FROM foodpanda
GROUP BY 1

-- 12  Calculate the Customer Lifetime Value (CLV) (total spend per customer_id).

SELECT
	customer_id,
	SUM(price) as total_spend
FROM foodpanda
GROUP BY 1

-- 13  Is there a visible correlation between customer age and the rating given?

SELECT
	CORR(age_int,rating)
FROM foodpanda
-- We have no corelation between age and rating.

-- 14 Which food category contributes the most to the total revenue?

SELECT
	category,
	ROUND(SUM(price)::numeric,2)
FROM foodpanda
GROUP BY 1
ORDER BY 2 DESC

-- 15 What is the average time lag between a customer's signup_date and their first order_date?
WITh table1
AS
(
SELECT
	customer_id,
	signup_date,
	MIN(order_date) AS first_order
FROM foodpanda
GROUP BY 1,2
)

SELECT
	ROUND((AVG(first_order - signup_date) * 24)::numeric,1) AS avg_time_in_hours
FROM table1

-- 16 What is the overall Churn Rate (percentage of customers where churned = Yes)?
WITH table1
AS
(
SELECT
	COUNT(*) AS with_churn
FROM foodpanda
WHERE churned = 'Active'
),

table2
AS
(
SELECT
	COUNT(*) AS total
FROM foodpanda
)

SELECT
	ROUND((with_churn / total::numeric)* 100::numeric,2)
FROM table1,table2

-- 17  List the top 5 most popular dishes in the city with the highest sales.
WITH table1
AS
(
SELECT
	city,
	dish_name,
	SUM(price) as total_sales
FROM foodpanda
GROUP BY 1,2
)

SELECT
	city,
	dish_name,
	RANK() OVER(PARTITION BY city ORDER BY total_sales DESC),
	ROUND(total_sales::numeric,1) AS total_sales_per_dishes
FROM table1
ORDER BY 1

-- 18  How does the monthly order volume trend over time (Seasonality analysis)?
with table1
AS
(
SELECT
	DATE_TRUNC('month', order_date) AS luna_an,
	COUNT(*) AS nr_comenzi
FROM foodpanda
GROUP BY 1
)

SELECT
	luna_an,
	nr_comenzi,
	LAG(nr_comenzi) OVER(ORDER BY luna_an) AS an_trecut,
	(nr_comenzi - LAG(nr_comenzi) OVER(ORDER BY luna_an)) * 100 / LAG(nr_comenzi) OVER(ORDER BY luna_an) AS procentaj
FROM table1

-- 19 Do customers with higher loyalty points tend to leave higher ratings?
with bigger
AS
(
SELECT 
	ROUND(AVG(rating)::numeric,2) AS high_loy
FROM foodpanda
WHERE loyalty_points > 250
),
smaller
AS
(
SELECT
	ROUND(AVG(rating)::numeric,2) AS low_loy
FROM foodpanda
WHERE loyalty_points < 250
)

SELECT
	bigger.high_loy,
	smaller.low_loy
FROM bigger,smaller

SELECT
	ROUND(CORR(loyalty_points, rating)::numeric,2)
FROM foodpanda

-- 20  What is the average basket size (quantity of items per order) for each city?
WITH table1
AS
(
SELECT
	city,
	order_id,
	SUM(quantity) AS total_per_order
FROM foodpanda
GROUP BY 1,2
ORDER BY 1
)

SELECT
	city,
	ROUND(AVG(total_per_order)::numeric,2)
FROM table1
GROUP BY 1
