


DROP TABLE IF EXISTS foodpanda
CREATE TABLE foodpanda(
customer_id	VARCHAR(15),
gender	VARCHAR(15),
age	VARCHAR(25),
city	VARCHAR(25),
signup_date	DATE,
order_id	VARCHAR(25),
order_date	DATE,
restaurant_name	VARCHAR(25),
dish_name	VARCHAR(25),
category	VARCHAR(25),
quantity	INT,
price	FLOAT,
payment_method	VARCHAR(25),	
order_frequency	INT,
last_order_date	DATE,
loyalty_points	INT,
churned	VARCHAR(25),
rating	INT,
rating_date	DATE,
delivery_status	VARCHAR(25),
age_int INT
)

SELECT *
FROM foodpanda

--	1  What is the total number of unique orders in the dataset?

SELECT
	COUNT(DISTINCT(order_date)) AS nr_of_unique_orders
FROM foodpanda

-- 2  How many unique customers are currently in our database?

SELECT
	COUNT(DISTINCT(customer_id)) AS nr_of_unique_customers
FROM foodpanda

-- 3  What is the average price of a dish across all restaurants?

SELECT
	ROUND(AVG(price)::numeric,2) AS avg_price
FROM foodpanda

-- 4  Which city has the highest volume of orders?
WITH table1
AS
(
SELECT
	city,
	COUNT(order_id) as nr_of_orders
FROM foodpanda
GROUP BY 1
)

SELECT
	city,
	RANK() OVER(ORDER BY nr_of_orders DESC)
FROM table1

-- 5  What is the most preferred payment method used by customers?

SELECT
	payment_method,
	COUNT(payment_method)
FROM foodpanda
GROUP BY 1
ORDER BY 2 DESC

-- 6  How many distinct restaurants are active on the platform?

SELECT
	COUNT(DISTINCT(restaurant_name))
FROM foodpanda

-- 7  What is the average loyalty points balance per customer?

WITH table1
AS
(
SELECT
	DISTINCT customer_id AS customer,
	loyalty_points
FROM foodpanda
)
SELECT
	customer,
	ROUND(AVG(loyalty_points)::numeric,2)
FROM table1
GROUP BY 1

-- 8  How many orders have a delivery_status of "Cancelled" or "Failed"?

SELECT
	COUNT(*)
FROM foodpanda
WHERE delivery_status = 'Cancelled' OR
delivery_status = 'Failed'

-- 9  What is the gender distribution of our customer base?

SELECT
	gender,
	COUNT(gender)
FROM foodpanda
GROUP BY 1

-- 10  What is the earliest and latest order_date in this dataset?

SELECT
	MIN(order_date) AS first_order,
	MAX(order_date) AS last_order
FROM foodpanda

-- 11  What is the total revenue generated by each restaurant?

SELECT
	restaurant_name,
	ROUND(SUM(price)::numeric,2)
FROM foodpanda
GROUP BY 1

-- 12  Calculate the Customer Lifetime Value (CLV) (total spend per customer_id).

SELECT
	customer_id,
	SUM(price) as total_spend
FROM foodpanda
GROUP BY 1

-- 13  Is there a visible correlation between customer age and the rating given?

SELECT
	CORR(age_int,rating)
FROM foodpanda
-- We have no corelation between age and rating.

-- 14 Which food category contributes the most to the total revenue?

SELECT
	category,
	ROUND(SUM(price)::numeric,2)
FROM foodpanda
GROUP BY 1
ORDER BY 2 DESC

-- 15 What is the average time lag between a customer's signup_date and their first order_date?
WITh table1
AS
(
SELECT
	customer_id,
	signup_date,
	MIN(order_date) AS first_order
FROM foodpanda
GROUP BY 1,2
)

SELECT
	ROUND((AVG(first_order - signup_date) * 24)::numeric,1) AS avg_time_in_hours
FROM table1

-- 16 What is the overall Churn Rate (percentage of customers where churned = Yes)?
WITH table1
AS
(
SELECT
	COUNT(*) AS with_churn
FROM foodpanda
WHERE churned = 'Active'
),

table2
AS
(
SELECT
	COUNT(*) AS total
FROM foodpanda
)

SELECT
	ROUND((with_churn / total::numeric)* 100::numeric,2)
FROM table1,table2

-- 17  List the top 5 most popular dishes in the city with the highest sales.
WITH table1
AS
(
SELECT
	city,
	dish_name,
	SUM(price) as total_sales
FROM foodpanda
GROUP BY 1,2
)

SELECT
	city,
	dish_name,
	RANK() OVER(PARTITION BY city ORDER BY total_sales DESC),
	ROUND(total_sales::numeric,1) AS total_sales_per_dishes
FROM table1
ORDER BY 1

-- 18  How does the monthly order volume trend over time (Seasonality analysis)?
with table1
AS
(
SELECT
	DATE_TRUNC('month', order_date) AS luna_an,
	COUNT(*) AS nr_comenzi
FROM foodpanda
GROUP BY 1
)

SELECT
	luna_an,
	nr_comenzi,
	LAG(nr_comenzi) OVER(ORDER BY luna_an) AS an_trecut,
	(nr_comenzi - LAG(nr_comenzi) OVER(ORDER BY luna_an)) * 100 / LAG(nr_comenzi) OVER(ORDER BY luna_an) AS procentaj
FROM table1

-- 19 Do customers with higher loyalty points tend to leave higher ratings?
with bigger
AS
(
SELECT 
	ROUND(AVG(rating)::numeric,2) AS high_loy
FROM foodpanda
WHERE loyalty_points > 250
),
smaller
AS
(
SELECT
	ROUND(AVG(rating)::numeric,2) AS low_loy
FROM foodpanda
WHERE loyalty_points < 250
)

SELECT
	bigger.high_loy,
	smaller.low_loy
FROM bigger,smaller

SELECT
	ROUND(CORR(loyalty_points, rating)::numeric,2)
FROM foodpanda

-- 20  What is the average basket size (quantity of items per order) for each city?
WITH table1
AS
(
SELECT
	city,
	order_id,
	SUM(quantity) AS total_per_order
FROM foodpanda
GROUP BY 1,2
ORDER BY 1
)

SELECT
	city,
	ROUND(AVG(total_per_order)::numeric,2)
FROM table1
GROUP BY 1

-- 21  RFM Segmentation: Assign a score to each customer based on Recency (last_order_date), Frequency (order_frequency), and Monetary value (total spend).
WITH customer_info
AS
(
SELECT
	customer_id,
	MAX(order_date) AS last_order,
	COUNT(order_id) AS frequency,
	SUM(price) as valuee,
	(CURRENT_DATE - MAX(order_date)) AS time_diff
FROM foodpanda
GROUP BY 1
),

score
AS
(
SELECT
	customer_id,
	NTILE(5) OVER(ORDER BY time_diff DESC) AS time_score,
	NTILE(5) OVER(ORDER BY valuee ASC) AS value_score,
	NTILE(5) OVER(ORDER BY frequency ASC) AS freq_score
FROM customer_info
)

SELECT
	customer_id,
	time_score,
	value_score,
	freq_score,
	CASE
	WHEN time_score >= 4 AND freq_score >= 4 THEN 'MVP'
	WHEN time_score >= 4 AND freq_score < 4 THEN 'LOST-MVPs'
	WHEN time_score <= 2 AND freq_score >= 4 THEN 'UPCOMING MVPs'
	WHEN time_score <=2 AND freq_score <=2 THEN 'LOSSERS'
	ELSE
	'ONE_TIME_CUSTOMER'
	END AS segmentation
FROM score
ORDER BY 5

-- 23  Anomaly Detection: Identify "Power Users" whose order frequency is more than 3 standard deviations above the mean.
with table1
AS
(
SELECT
	customer_id,
	COUNT(*) order_count
FROM foodpanda
GROUP BY 1
),

table2
AS
(
SELECT
	AVG(table1.order_count) AS avg_freq
	STDDEV(order_count) AS std_dev
FROM table1
)

SELECT
	customer_id,
	order_count
FROM table1,table2
WHERE order_count > avg_freq + (3 * std_dev)

-- 25  Re-engagement Logic: Based on order_frequency and last_order_date, list customers who are "overdue" for an order today.
WITH table1
AS
(
SELECT
	customer_id,
	COUNT(*),
	MAX(order_date) AS last_order,
	MIN(order_date),
	(MAX(order_date) - MIN(order_date)),
	ROUND((MAX(order_date) - MIN(order_date)) / COUNT(*)::numeric,2) AS AVG_order_days
FROM foodpanda
GROUP BY 1
)

SELECT
	customer_id
FROM table1
WHERE (CURRENT_DATE - last_order) > AVG_order_days

-- 26  Performance Decay: Identify restaurants that have seen a consistent decline in average ratings over the last 6 months.
-- latest order is 2025-08-22
WITH table1
AS
(
SELECT
	restaurant_name,
	AVG(rating) AS avg_rating,
	DATE_TRUNC('month', order_date) AS monthh
FROM foodpanda
WHERE order_date >= '2025-03-01'
GROUP BY 1,3

),

table2
AS
(
SELECT
	restaurant_name,
	avg_rating,
	monthh,
	LAG(avg_rating) OVER(PARTITION BY restaurant_name ORDER BY monthh) AS last_month_avg
FROM table1
)

SELECT
	restaurant_name,
	avg_rating,
	last_month_avg,
	monthh
FROM table2
WHERE avg_rating < last_month_avg 
	AND
	last_month_avg IS NOT NULL
ORDER BY 1,4

-- 27  Market Basket Analysis: Identify which categories or dishes are most frequently bought together in the same order_id.
-- counter starts from 230 to 270 so i think that frequently is more than 250
SELECT
	category,
	dish_name,
	COUNT(dish_name) AS counter
FROM foodpanda
GROUP BY 1,2
HAVING COUNT(dish_name) > 250
ORDER BY 1
