DROP TABLE IF EXISTS customerss
CREATE TABLE customerss (
customer_id	INT PRIMARY KEY,
age	INT,
gender	VARCHAR(20),
item_purchased	VARCHAR(20),
category	VARCHAR(20),
purchase_amount	INT,
location	VARCHAR(20),
size	VARCHAR(10),
color	VARCHAR(20),
season	VARCHAR(20),
review_rating	FLOAT,
subscription_status	VARCHAR(10),
shipping_type	VARCHAR(20),
discount_applied	VARCHAR(10),
previous_purchases	INT,
payment_method	VARCHAR(20),
frequency_of_purchases	VARCHAR(20),
age_group	VARCHAR(20),
int_frequency	INT
)

SELECT *
FROM customerr

-- what is the total revenue generated by male and female customers

SELECT
	gender,
	SUM(purchase_amount) as total_rev
FROM customerr 
GROUP BY 1

-- which customer used discount but still spend more than the average purchase ammount?
with table1
AS
(
SELECT
	customer_id,
	SUM(purchase_amount) as total_spent
FROM customerr
WHERE discount_applied = 'Yes'
GROUP BY 1
)

SELECT *
FROM table1
WHERE total_spent >= (SELECT AVG(purchase_amount) FROM customerr)
